version: '3.8'

services:
  cutter:
    build:
      context: .
      dockerfile: cutter.dockerfile
    volumes:
      - /home/dev/projects/deploy_hml/data_all:/app/data_all
    tty:
      true
    env_file:
      - .env
    ports:
      - "6000:6000"
    environment:
      - CLUST_RES_PATH=/app/data_all/clusters_use_dg1.json
      - EMB_RES_PATH=/app/data_all/use_embeddings_dg1.pkl
      - CENT_PATH=/app/data_all/clusters_centers_use_dg1.pkl
      - S3_KEY_ID=${S3_KEY_ID}
      - S3_SECRET=${S3_SECRET}
      - S3_URL=${S3_URL}
      - S3_PREFIX=${S3_PREFIX}
      - S3_BUCKET=${S3_BUCKET}
